#!/usr/bin/env python3
# infile is the name of the file
# run file is "~/Desktop/imagecrop.py *.jpg"
from PIL import Image, ImageEnhance
import sys
imgnum = 1
width = 250
height = 380
# REMIND CODING PPL IT MUST BE THIS SIZE
xfudge = 0
yfudge = 100
for infile in sys.argv[1:]:
	crops = [
		[300 + xfudge,20 + yfudge,0,0],
		[285 + xfudge,35 + yfudge,0,0], 
		[315 + xfudge,35 + yfudge,0,0],
		[315 + xfudge,5 + yfudge,0,0],
		[285 + xfudge,5 + yfudge,0,0]
		]
	brightnesses = [0.8,0.9,1.0,1.1,1.2]
	print('working on file;' + infile)
	with Image.open(infile)as img:
		for crop in crops:
			crop[2] = crop[0] + widt
			crop[3] = crop[1] + height
			cropimg = img.crop(crop)
			#(left,upper,right,lower) 
			enhancer = ImageEnhance.Brightness(cropimg)
			for brightness in brightnesses:
				timg= enhancer.enhance(brightness)
				timg.save(str(imgnum) + '.png')
				imgnum +=1
			
