#!/usr/bin/env python3
#Do not remove 1st line; this must be run in linux terminal
# infile is the name of the file
# run file is "~/Desktop/imagecrop.py *.jpg"
from PIL import Image, ImageEnhance
import sys
# imports necessary image packages
imgnum = 1
#enables you to crop multiple images
width = 250
height = 380
#measured by pixels
# REMIND CODING PPL IT MUST BE THIS SIZE
xfudge = 0
yfudge = 100
#height and width added varies based on what size you want to crop
#is measured by pixels
for infile in sys.argv[1:]:
	crops = [
		[300 + xfudge,20 + yfudge,0,0],
		[285 + xfudge,35 + yfudge,0,0], 
		[315 + xfudge,35 + yfudge,0,0],
		[315 + xfudge,5 + yfudge,0,0],
		[285 + xfudge,5 + yfudge,0,0]
		]
		#(left,upper,right,lower) 
	brightnesses = [0.8,0.9,1.0,1.1,1.2]
	#crops multiple copies of an image to enable the best results for tensorflow
	print('working on file;' + infile)
	#tells you it is working on a files
	with Image.open(infile)as img:
		for crop in crops:
			crop[2] = crop[0] + width
			crop[3] = crop[1] + height
			cropimg = img.crop(crop)
			#crops image
			enhancer = ImageEnhance.Brightness(cropimg)
			for brightness in brightnesses:
				timg= enhancer.enhance(brightness)
				timg.save(str(imgnum) + '.png')
				imgnum +=1
				#applies brightness enhancer
			
			
#Pillow articles to help:
#https://pythonexamples.org/python-pillow-adjust-image-brightness/#3 
#https://www.geeksforgeeks.org/python-pil-image-crop-method/
#https://www.tutorialspoint.com/python_pillow/index.htm
#https://pillow.readthedocs.io/en/stable/handbook/tutorial.html
